triple-store:
  sparql-endpoint:
#  auth:
#    method:   # BASIC or DIGEST
#    username:
#    password:
#  graph:
#    class:
#    named:
#    type:
#
#fdp:
#  token:
#  distribution:
#
#security:
#  token:
